grid_bfs   48577 72433.950274:    9340896 cpu_atom/cycles/P: 
	    625abf25bfcc generate_grid[abi:cxx11](int, int)+0x2fc (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf259644 main+0x74 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72433.952813:   15845697 cpu_atom/cycles/P: 
	    625abf259f4f shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x21f (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72433.957113:   26263669 cpu_atom/cycles/P: 
	    625abf259ec7 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x197 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72433.964234:   32939024 cpu_atom/cycles/P: 
	    625abf259f27 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1f7 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72433.967277:    9708920 cpu_core/cycles/P: 
	    625abf259f12 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1e2 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72433.969235:   19173808 cpu_core/cycles/P: 
	    625abf259f57 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x227 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72433.973350:   36586906 cpu_core/cycles/P: 
	    625abf259eff shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1cf (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72433.980832:   44253173 cpu_core/cycles/P: 
	    625abf259ef0 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1c0 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72433.989709:   48520577 cpu_core/cycles/P: 
	    625abf259f27 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1f7 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72433.999575:   49355794 cpu_core/cycles/P: 
	    625abf259f7a shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x24a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.009678:   49438427 cpu_core/cycles/P: 
	    625abf259f27 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1f7 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.019689:   49724719 cpu_core/cycles/P: 
	    625abf259ef4 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1c4 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.029738:   49766404 cpu_core/cycles/P: 
	ffffffffb7ba6e59 perf_event_mmap_output+0x59 ([kernel.kallsyms])
	ffffffffb7b9f023 perf_iterate_ctx+0x33 ([kernel.kallsyms])
	ffffffffb7b9ff77 perf_iterate_sb.constprop.0+0x167 ([kernel.kallsyms])
	ffffffffb7ba0577 perf_event_mmap_event+0x1d7 ([kernel.kallsyms])
	ffffffffb7bb0e7b perf_event_mmap+0xdb ([kernel.kallsyms])
	ffffffffb7c3ad5f do_brk_flags+0x1df ([kernel.kallsyms])
	ffffffffb7c3b582 __do_sys_brk+0x322 ([kernel.kallsyms])
	ffffffffb7c3b6c2 __x64_sys_brk+0x12 ([kernel.kallsyms])
	ffffffffb780747b x64_sys_call+0x1b4b ([kernel.kallsyms])
	ffffffffb8a4c83f do_syscall_64+0x7f ([kernel.kallsyms])
	ffffffffb8c00130 entry_SYSCALL_64_after_hwframe+0x78 ([kernel.kallsyms])
	    7acc4591d7ab __brk+0xb (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc458aaa26 __default_morecore@GLIBC_2.2.5+0x16 (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc458acbf7 _int_malloc+0x1687 (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc458ad812 malloc+0x1a2 (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc45cbb904 operator new(unsigned long)+0x24 (/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.33)
	    625abf259e13 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0xe3 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.039998:   49085668 cpu_core/cycles/P: 
	    625abf259e40 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x110 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.050264:   48515257 cpu_core/cycles/P: 
	    625abf259f7e shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x24e (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.060211:   49014235 cpu_core/cycles/P: 
	    625abf259f4b shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x21b (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.070326:   49145201 cpu_core/cycles/P: 
	ffffffffb8a4e401 sync_regs+0x21 ([kernel.kallsyms])
	    625abf259e47 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x117 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.080618:   48361640 cpu_core/cycles/P: 
	    625abf259eff shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1cf (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.090576:   48892645 cpu_core/cycles/P: 
	    7acc4598954c __memset_avx2_unaligned_erms+0xcc (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.100631:   49182978 cpu_core/cycles/P: 
	    625abf259ef4 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1c4 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.110877:   48896910 cpu_core/cycles/P: 
	    625abf259efa shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1ca (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.121004:   48937550 cpu_core/cycles/P: 
	    625abf259f1c shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1ec (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.131081:   49152324 cpu_core/cycles/P: 
	    625abf259f7e shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x24e (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.141520:   48180992 cpu_core/cycles/P: 
	    625abf259f22 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1f2 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.151626:   48284209 cpu_core/cycles/P: 
	    625abf259f1c shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1ec (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.161683:   48444028 cpu_core/cycles/P: 
	    625abf259f4b shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x21b (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.171805:   48351313 cpu_core/cycles/P: 
	    625abf259f27 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1f7 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.181948:   48417730 cpu_core/cycles/P: 
	    625abf259f27 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1f7 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.192454:   46946133 cpu_core/cycles/P: 
	    625abf259ef4 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1c4 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.202633:   46578037 cpu_core/cycles/P: 
	    625abf259ed1 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1a1 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.212571:   47320278 cpu_core/cycles/P: 
	    625abf259f37 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x207 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.222554:   47837639 cpu_core/cycles/P: 
	    625abf259f27 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1f7 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.232814:   47648537 cpu_core/cycles/P: 
	    625abf259f7a shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x24a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.242792:   48007927 cpu_core/cycles/P: 
	    625abf259f19 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1e9 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.252753:   48311181 cpu_core/cycles/P: 
	    625abf259ef0 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1c0 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.262937:   47854296 cpu_core/cycles/P: 
	    625abf259f7e shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x24e (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.273109:   47377474 cpu_core/cycles/P: 
	    625abf259f7e shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x24e (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.283150:   47517971 cpu_core/cycles/P: 
	    625abf259f42 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x212 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.293596:   45560208 cpu_core/cycles/P: 
	    625abf259f42 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x212 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.303396:   46512767 cpu_core/cycles/P: 
	    625abf259e47 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x117 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.313149:   47567471 cpu_core/cycles/P: 
	    625abf259f42 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x212 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.323260:   47888669 cpu_core/cycles/P: 
	    625abf259f34 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x204 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.333419:   47635448 cpu_core/cycles/P: 
	    625abf259eff shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1cf (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.343412:   48059563 cpu_core/cycles/P: 
	    625abf259efa shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1ca (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.353391:   48389560 cpu_core/cycles/P: 
	    625abf259f27 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1f7 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.362225:   10074125 cpu_core/cycles/P: 
	    625abf259f7e shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x24e (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.364397:   18773830 cpu_core/cycles/P: 
	    625abf259f27 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1f7 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.368279:   31162788 cpu_core/cycles/P: 
	    625abf259f27 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1f7 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.374665:   41051248 cpu_core/cycles/P: 
	ffffffffb7bd76d1 lru_gen_add_folio+0x121 ([kernel.kallsyms])
	ffffffffb7bd8686 lru_add_fn+0xb6 ([kernel.kallsyms])
	ffffffffb7bd955f folio_batch_move_lru+0xaf ([kernel.kallsyms])
	ffffffffb7bd96b1 folio_add_lru+0x71 ([kernel.kallsyms])
	ffffffffb7bda68f folio_add_lru_vma+0x1f ([kernel.kallsyms])
	ffffffffb7c2f6d1 do_anonymous_page+0x371 ([kernel.kallsyms])
	ffffffffb7c3058b handle_pte_fault+0x1cb ([kernel.kallsyms])
	ffffffffb7c30bf4 __handle_mm_fault+0x654 ([kernel.kallsyms])
	ffffffffb7c30eca handle_mm_fault+0x18a ([kernel.kallsyms])
	ffffffffb78d7f79 do_user_addr_fault+0x169 ([kernel.kallsyms])
	ffffffffb8a52bb3 exc_page_fault+0x83 ([kernel.kallsyms])
	ffffffffb8c00bc7 asm_exc_page_fault+0x27 ([kernel.kallsyms])
	    625abf259e47 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x117 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.383179:   46511321 cpu_core/cycles/P: 
	    625abf259f7e shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x24e (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.392569:   49043575 cpu_core/cycles/P: 
	    625abf259f27 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1f7 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.402467:   49794142 cpu_core/cycles/P: 
	ffffffffb7cceab1 __count_memcg_events+0x31 ([kernel.kallsyms])
	ffffffffb7cd1ec2 mem_cgroup_commit_charge+0xa2 ([kernel.kallsyms])
	ffffffffb7cd393a __mem_cgroup_charge+0x5a ([kernel.kallsyms])
	ffffffffb7c2f412 do_anonymous_page+0xb2 ([kernel.kallsyms])
	ffffffffb7c3058b handle_pte_fault+0x1cb ([kernel.kallsyms])
	ffffffffb7c30bf4 __handle_mm_fault+0x654 ([kernel.kallsyms])
	ffffffffb7c30eca handle_mm_fault+0x18a ([kernel.kallsyms])
	ffffffffb78d7f79 do_user_addr_fault+0x169 ([kernel.kallsyms])
	ffffffffb8a52bb3 exc_page_fault+0x83 ([kernel.kallsyms])
	ffffffffb8c00bc7 asm_exc_page_fault+0x27 ([kernel.kallsyms])
	    625abf259e47 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x117 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.412456:   50184369 cpu_core/cycles/P: 
	    625abf259ef0 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1c0 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.422583:   49963540 cpu_core/cycles/P: 
	ffffffffb7c45c2c __pte_offset_map+0x5c ([kernel.kallsyms])
	ffffffffb7c45eb5 __pte_offset_map_lock+0x45 ([kernel.kallsyms])
	ffffffffb7c2f4a3 do_anonymous_page+0x143 ([kernel.kallsyms])
	ffffffffb7c3058b handle_pte_fault+0x1cb ([kernel.kallsyms])
	ffffffffb7c30bf4 __handle_mm_fault+0x654 ([kernel.kallsyms])
	ffffffffb7c30eca handle_mm_fault+0x18a ([kernel.kallsyms])
	ffffffffb78d7f79 do_user_addr_fault+0x169 ([kernel.kallsyms])
	ffffffffb8a52bb3 exc_page_fault+0x83 ([kernel.kallsyms])
	ffffffffb8c00bc7 asm_exc_page_fault+0x27 ([kernel.kallsyms])
	    625abf259e47 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x117 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.432635:   50176461 cpu_core/cycles/P: 
	    625abf259f4b shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x21b (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.442731:   50114853 cpu_core/cycles/P: 
	    625abf259f6b shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x23b (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.452782:   50301774 cpu_core/cycles/P: 
	    625abf259f09 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1d9 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.462870:   50353413 cpu_core/cycles/P: 
	    625abf259efa shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1ca (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.472969:   50358801 cpu_core/cycles/P: 
	    625abf259e40 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x110 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.483068:   50368563 cpu_core/cycles/P: 
	    625abf259f7a shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x24a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.493355:   49779663 cpu_core/cycles/P: 
	    625abf259f27 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1f7 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.503419:   49955151 cpu_core/cycles/P: 
	    625abf259f1c shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1ec (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.513493:   50090055 cpu_core/cycles/P: 
	    625abf259eee shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1be (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.523598:   50065111 cpu_core/cycles/P: 
	    625abf259f5f shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x22f (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.533769:   49908277 cpu_core/cycles/P: 
	    625abf259f27 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1f7 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.543796:   50164746 cpu_core/cycles/P: 
	    625abf259f27 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1f7 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.553875:   50248005 cpu_core/cycles/P: 
	    625abf259f6b shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x23b (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.563953:   50338261 cpu_core/cycles/P: 
	    625abf259f27 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1f7 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.574052:   50344778 cpu_core/cycles/P: 
	    625abf259f6b shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x23b (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.584171:   50290155 cpu_core/cycles/P: 
	    625abf259f29 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1f9 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.594263:   50317919 cpu_core/cycles/P: 
	    625abf259f7a shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x24a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.604354:   50356754 cpu_core/cycles/P: 
	    625abf259f27 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1f7 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.614513:   50125402 cpu_core/cycles/P: 
	    625abf259f27 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1f7 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.624594:   50239778 cpu_core/cycles/P: 
	    625abf259f12 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1e2 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.634701:   50180301 cpu_core/cycles/P: 
	    625abf259f29 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1f9 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.644778:   50277975 cpu_core/cycles/P: 
	    625abf259f7a shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x24a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.654869:   50306842 cpu_core/cycles/P: 
	    625abf259f1c shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1ec (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.664998:   50263056 cpu_core/cycles/P: 
	ffffffffb7c45f44 __pte_offset_map_lock+0xd4 ([kernel.kallsyms])
	ffffffffb7c2f4a3 do_anonymous_page+0x143 ([kernel.kallsyms])
	ffffffffb7c3058b handle_pte_fault+0x1cb ([kernel.kallsyms])
	ffffffffb7c30bf4 __handle_mm_fault+0x654 ([kernel.kallsyms])
	ffffffffb7c30eca handle_mm_fault+0x18a ([kernel.kallsyms])
	ffffffffb78d7f79 do_user_addr_fault+0x169 ([kernel.kallsyms])
	ffffffffb8a52bb3 exc_page_fault+0x83 ([kernel.kallsyms])
	ffffffffb8c00bc7 asm_exc_page_fault+0x27 ([kernel.kallsyms])
	    625abf259e47 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x117 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.675080:   50338375 cpu_core/cycles/P: 
	    625abf259f7e shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x24e (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.685204:   50292574 cpu_core/cycles/P: 
	    625abf259f8c shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x25c (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.695339:   50068713 cpu_core/cycles/P: 
	    625abf259ed1 shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1a1 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.705636:   49268346 cpu_core/cycles/P: 
	    625abf259efa shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1ca (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.715776:   49103215 cpu_core/cycles/P: 
	    625abf259efa shortest_path_bfs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, RouteRequest const&, std::vector<int, std::allocator<int> >&)+0x1ca (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b1cb run_all_requests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<RouteRequest, std::allocator<RouteRequest> > const&, std::vector<int, std::allocator<int> >&)+0xfb (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596ae main+0xde (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.725920:   48962036 cpu_core/cycles/P: 
	    625abf25a204 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x44 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.736194:   48588869 cpu_core/cycles/P: 
	    625abf25a223 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x63 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.746918:   46688194 cpu_core/cycles/P: 
	    625abf25a223 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x63 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.756611:   48107819 cpu_core/cycles/P: 
	    625abf25a1f6 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x36 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.766803:   47711522 cpu_core/cycles/P: 
	    625abf25a1ca next_pressure_value(int, int, int, int, int, int, int, int, int)+0xa (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.776924:   47530644 cpu_core/cycles/P: 
	    625abf25a204 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x44 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.787874:   48311674 cpu_core/cycles/P: 
	    625abf25b8bf compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x30f (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.798143:   47594844 cpu_core/cycles/P: 
	    625abf25b8ba compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x30a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.808153:   47937205 cpu_core/cycles/P: 
	    625abf25b8d5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x325 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.818230:   47772794 cpu_core/cycles/P: 
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.828333:   47963690 cpu_core/cycles/P: 
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.838574:   47450925 cpu_core/cycles/P: 
	    625abf25b8c9 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x319 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.848529:   47688802 cpu_core/cycles/P: 
	    625abf25b8ba compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x30a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.858461:   48454832 cpu_core/cycles/P: 
	    625abf25a20f next_pressure_value(int, int, int, int, int, int, int, int, int)+0x4f (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.868612:   48339004 cpu_core/cycles/P: 
	    625abf25a204 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x44 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.878696:   48385554 cpu_core/cycles/P: 
	    625abf25a22d next_pressure_value(int, int, int, int, int, int, int, int, int)+0x6d (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.888810:   48302166 cpu_core/cycles/P: 
	    625abf25a238 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x78 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.899018:   47887481 cpu_core/cycles/P: 
	    625abf25a1f6 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x36 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.908903:   48578756 cpu_core/cycles/P: 
	    625abf25a204 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x44 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.919101:   48281563 cpu_core/cycles/P: 
	    625abf25b8f5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x345 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.929244:   48131812 cpu_core/cycles/P: 
	    625abf25a22d next_pressure_value(int, int, int, int, int, int, int, int, int)+0x6d (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.939361:   48097966 cpu_core/cycles/P: 
	    625abf25b8dc compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x32c (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.949382:   48340171 cpu_core/cycles/P: 
	    625abf25b8f5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x345 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.959626:   47805734 cpu_core/cycles/P: 
	    625abf25a1f6 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x36 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.969624:   48168302 cpu_core/cycles/P: 
	    625abf25b8ba compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x30a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.979770:   48013388 cpu_core/cycles/P: 
	    625abf25a1e0 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x20 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.989799:   48267134 cpu_core/cycles/P: 
	    625abf25b8c9 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x319 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72434.999935:   48109756 cpu_core/cycles/P: 
	    625abf25a223 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x63 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.010179:   47818416 cpu_core/cycles/P: 
	    625abf25a20f next_pressure_value(int, int, int, int, int, int, int, int, int)+0x4f (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.020380:   47583175 cpu_core/cycles/P: 
	    625abf25a1ea next_pressure_value(int, int, int, int, int, int, int, int, int)+0x2a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.030652:   46938286 cpu_core/cycles/P: 
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.040468:   47954944 cpu_core/cycles/P: 
	    625abf25b8c9 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x319 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.050508:   48221864 cpu_core/cycles/P: 
	    625abf25a1f6 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x36 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.060690:   47954057 cpu_core/cycles/P: 
	    625abf25a204 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x44 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.070784:   47930804 cpu_core/cycles/P: 
	    625abf25b8c9 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x319 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.080854:   48093500 cpu_core/cycles/P: 
	    625abf25b8dc compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x32c (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.090907:   48274344 cpu_core/cycles/P: 
	    625abf25b8dc compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x32c (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.101091:   47999149 cpu_core/cycles/P: 
	    625abf25a1c0 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x0 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.111211:   47998507 cpu_core/cycles/P: 
	    625abf25a1c0 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x0 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.121249:   48233972 cpu_core/cycles/P: 
	    625abf25a238 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x78 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.131504:   47626717 cpu_core/cycles/P: 
	    625abf25b8a8 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x2f8 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.141748:   47068553 cpu_core/cycles/P: 
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.151965:   46802455 cpu_core/cycles/P: 
	    625abf25b8c9 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x319 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.161828:   47546406 cpu_core/cycles/P: 
	    625abf25a1d3 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x13 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.171776:   48109591 cpu_core/cycles/P: 
	    625abf25a20f next_pressure_value(int, int, int, int, int, int, int, int, int)+0x4f (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.181903:   48027633 cpu_core/cycles/P: 
	    625abf25a1d3 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x13 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.192132:   47484760 cpu_core/cycles/P: 
	    625abf25a20f next_pressure_value(int, int, int, int, int, int, int, int, int)+0x4f (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.202069:   47844301 cpu_core/cycles/P: 
	    625abf25a1e0 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x20 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.212053:   48242886 cpu_core/cycles/P: 
	    625abf25b8f5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x345 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.222316:   47533529 cpu_core/cycles/P: 
	    625abf25a1c0 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x0 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.232482:   47302380 cpu_core/cycles/P: 
	    625abf25b8f5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x345 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.242655:   47187672 cpu_core/cycles/P: 
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.252538:   47938535 cpu_core/cycles/P: 
	    625abf25a22d next_pressure_value(int, int, int, int, int, int, int, int, int)+0x6d (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.262687:   47821461 cpu_core/cycles/P: 
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.272748:   47906155 cpu_core/cycles/P: 
	    625abf25b8ba compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x30a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.282865:   47973463 cpu_core/cycles/P: 
	    625abf25b8dc compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x32c (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.293009:   47855308 cpu_core/cycles/P: 
	    625abf25b8dc compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x32c (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.303139:   47640442 cpu_core/cycles/P: 
	    625abf25a238 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x78 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.313191:   47776884 cpu_core/cycles/P: 
	    625abf25b8c9 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x319 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.323363:   47493736 cpu_core/cycles/P: 
	    625abf25a223 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x63 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.333393:   47701782 cpu_core/cycles/P: 
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.343525:   47658698 cpu_core/cycles/P: 
	    625abf25a1ca next_pressure_value(int, int, int, int, int, int, int, int, int)+0xa (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.353586:   47673887 cpu_core/cycles/P: 
	    625abf25a20f next_pressure_value(int, int, int, int, int, int, int, int, int)+0x4f (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.363623:   47670624 cpu_core/cycles/P: 
	    625abf25b8a8 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x2f8 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.373598:   48272167 cpu_core/cycles/P: 
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.383701:   48247349 cpu_core/cycles/P: 
	    625abf25a204 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x44 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.393980:   47480889 cpu_core/cycles/P: 
	    625abf25a1f6 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x36 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.404030:   47581275 cpu_core/cycles/P: 
	    625abf25a223 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x63 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.414145:   47459239 cpu_core/cycles/P: 
	    625abf25a204 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x44 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.424197:   47717563 cpu_core/cycles/P: 
	    625abf25a1ca next_pressure_value(int, int, int, int, int, int, int, int, int)+0xa (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.434267:   47822065 cpu_core/cycles/P: 
	    625abf25a21a next_pressure_value(int, int, int, int, int, int, int, int, int)+0x5a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.444459:   47510313 cpu_core/cycles/P: 
	    625abf25a245 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x85 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.454822:   46264686 cpu_core/cycles/P: 
	    625abf25b8d5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x325 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.464444:   48005262 cpu_core/cycles/P: 
	    625abf25a245 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x85 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.474614:   47818651 cpu_core/cycles/P: 
	    625abf25b8dc compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x32c (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.484871:   47510476 cpu_core/cycles/P: 
	    625abf25a21a next_pressure_value(int, int, int, int, int, int, int, int, int)+0x5a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.494998:   47435389 cpu_core/cycles/P: 
	    625abf25a1f6 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x36 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.505202:   47122298 cpu_core/cycles/P: 
	    625abf25b8a8 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x2f8 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.515311:   47284404 cpu_core/cycles/P: 
	    625abf25a1d3 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x13 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.525329:   47617985 cpu_core/cycles/P: 
	    625abf25a22d next_pressure_value(int, int, int, int, int, int, int, int, int)+0x6d (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.535385:   47672661 cpu_core/cycles/P: 
	    625abf25a1d3 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x13 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.545352:   48156608 cpu_core/cycles/P: 
	    625abf25b8dc compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x32c (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.555565:   47854781 cpu_core/cycles/P: 
	    625abf25b8dc compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x32c (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.565621:   48099617 cpu_core/cycles/P: 
	    625abf25b8dc compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x32c (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.575883:   47520397 cpu_core/cycles/P: 
	    625abf25a1c0 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x0 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.585833:   48001617 cpu_core/cycles/P: 
	    625abf25b8dc compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x32c (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.595995:   47684097 cpu_core/cycles/P: 
	    625abf25b8d5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x325 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.606047:   47730582 cpu_core/cycles/P: 
	    625abf25b8a8 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x2f8 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.616174:   47366878 cpu_core/cycles/P: 
	    625abf25a204 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x44 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.626114:   47986711 cpu_core/cycles/P: 
	    625abf25a245 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x85 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

grid_bfs   48577 72435.636397:   47817871 cpu_core/cycles/P: 
	    625abf25a245 next_pressure_value(int, int, int, int, int, int, int, int, int)+0x85 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf25b8e5 compute_congestion_pressure(std::vector<int, std::allocator<int> > const&, int, int, int)+0x335 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    625abf2596fa main+0x12a (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)
	    7acc4582a1ca __libc_start_call_main+0x7a (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    7acc4582a28b __libc_start_main@@GLIBC_2.34+0x8b (/usr/lib/x86_64-linux-gnu/libc.so.6)
	    625abf2598a5 _start+0x25 (/home/mrjithin/bootcamp/bootcamp-coding-labs/assignment4-profiling/lab1/before/grid_bfs)

